Added scroll to top button with progress
4darsh-Dev/CogniGaurd pull request #117
Opened 2024-06-25 19:26 UTC by TheNikhilRaj

@4darsh-Dev 
Added scroll to top button with progress!
#80 
![Capture](https://github.com/4darsh-Dev/CogniGaurd/assets/129590267/891d9db9-85b3-4f19-83df-f86772f475da)

2024-06-25 19:41 UTC, TheNikhilRaj commented
please help me in the deployment?
give me the old code of settings.py and urls.py code which i can put it for deployment.
@4darsh-Dev

2024-06-26 05:46 UTC, 4darsh-Dev requested changes
## Some minor changes required
1. Your changes in settings.py and urls.py doesn't match with latest code from main branch, 
2. Issue might be due to not syncing the repo
3. Ensure that code written in settings. and urls.py remain same as main branch latest code in github repo

2024-06-26 05:46 UTC, 4darsh-Dev commented on django-web-app/cogniguard/settings.py
> -# email backend configuration
why have you removed email configuration, 
See the latest file of main branch
fix it

2024-06-26 05:46 UTC, 4darsh-Dev commented on django-web-app/cogniguard/urls.py
> -    # for rendering reset password cnf template
same issue, 
you've removed some paths required for password reset which have been added in recent commit. 
fix it.

2024-06-26 05:48 UTC, 4darsh-Dev commented
@TheNikhilRaj check for code in cogniguard github repo, latest from main branch

2024-06-26 05:50 UTC, TheNikhilRaj commented
@4darsh-Dev I have done this same thing but giving error ! What should do??

2024-06-26 06:21 UTC, 4darsh-Dev commented
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

2024-06-26 06:23 UTC, 4darsh-Dev commented
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

2024-06-26 06:47 UTC, TheNikhilRaj commented
@4darsh-Dev  it's done!

2024-06-26 16:55 UTC, 4darsh-Dev commented
@TheNikhilRaj i;ve reviewd already , fix the changes 
can you see the diff now
##ss
![Screenshot 2024-06-26 222241](https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/4c0e2086-0ce2-4b70-bb8c-b0197547da81)


![Screenshot 2024-06-26 222241](https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/1cc6089c-5abf-4de5-b7e4-1f85571e7f7d)

2024-06-26 16:58 UTC, 4darsh-Dev commented
![Screenshot 2024-06-26 222756](https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/b5dff80c-4360-4469-8a5b-b0ce452ae9fc)

2024-06-26 16:59 UTC, 4darsh-Dev requested changes
fix now

2024-06-27 08:15 UTC, TheNikhilRaj commented
> ![Screenshot 2024-06-26 222756](https://private-user-images.githubusercontent.com/109789509/343254894-b5dff80c-4360-4469-8a5b-b0ce452ae9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzU4MDcsIm5iZiI6MTcxOTQ3NTUwNywicGF0aCI6Ii8xMDk3ODk1MDkvMzQzMjU0ODk0LWI1ZGZmODBjLTQzNjAtNDQ2OS04YTViLWIwY2U0NTJhZTlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwODA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTJlZWVjODA2ZTU4NGU4ODc2YzdhOTFhNWJmMDFiYWU5ZjQyNmRjMmU5NGE4MDhiZmE5MmRiN2RmZDMzZTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l2gLwS5mTt4G0MVg7jOC8WgJjmmvPcyvG9E483Pce-s)

check the video clip as mentioned above 
@4darsh-Dev

2024-06-27 17:11 UTC, 4darsh-Dev reviewed
## See the vercel preview of your fork link and the main repository, 
and tell me where is the error ?
@TheNikhilRaj 

https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/140f051c-0654-4aaa-bfc0-fd022e055326

2024-06-29 11:00 UTC, TheNikhilRaj commented
@4darsh-Dev  Give me the old code of settings.py and urls.py on that basis i can do changes in the error!

2024-06-29 17:48 UTC, 4darsh-Dev commented
@TheNikhilRaj 
navigate to the project dir : django-web-app/cogniguard/settings.py 
similar for urls.py 
-- and add look for changes

2024-06-29 18:08 UTC, TheNikhilRaj commented
> @TheNikhilRaj 
> navigate to the project dir : django-web-app/cogniguard/settings.py 
> similar for urls.py 
> -- and add look for changes

Project dir? @4darsh-Dev

2024-06-29 20:03 UTC, 4darsh-Dev commented
@TheNikhilRaj  yes, 
https://github.com/4darsh-Dev/CogniGaurd/blob/main/django-web-app/cogniguard/settings.py

2024-07-03 06:43 UTC, closed without merging