Resolved issue #138,#137,#136,#135,#134
4darsh-Dev/CogniGaurd pull request #153
Opened 2024-07-19 10:44 UTC by Garima-149

@4darsh-Dev Please merge it and assign the labels as required.I tried to make 2 pr's but it comitted in single one.

2024-07-19 13:57 UTC, 4darsh-Dev requested changes
good work, 
### Some changes are required. 
i've mentioned them in conversation

After fixing position issue, the preview I'm getting for chatbot. 
## SS
![Screenshot 2024-07-19 192244](https://github.com/user-attachments/assets/82738c07-e1c5-4dfc-b99e-fbf7999bb369)

1. .message-bot background color is too light, make it little dark for proper visibility of text
2. It would be better if pressing enter will also send the message.

2024-07-19 13:57 UTC, 4darsh-Dev commented on django-web-app/templates/base.html
> +                    <a style="color: black;" target="_blank" href="https://github.com/4darsh-Dev/CogniGuard"><i
Here are two icons for github, remove one.

2024-07-19 13:57 UTC, 4darsh-Dev commented on django-web-app/static/css/style.css
> +  font-size: 40px; /* Adjust this size as needed */
much bigger icon , change to 32px

2024-07-19 13:57 UTC, 4darsh-Dev commented on django-web-app/static/css/style.css
> +  left:-170px ;
not visible, 
left : 80px ;

2024-07-19 13:57 UTC, 4darsh-Dev commented on django-web-app/static/css/style.css
> +  left:-170px ;
not visible on screen : 
use left:5rem;

2024-07-19 16:45 UTC, Garima-149 commented
@4darsh-Dev I did these css changes.please check

2024-07-20 03:57 UTC, 4darsh-Dev approved these changes
okay there are still some code scanning warnings
i'll fix them later.

2024-07-20 03:59 UTC, merged

2024-07-20 04:00 UTC, 4darsh-Dev commented
@Garima-149 , mark the issues as completed, 
PR is merged.

2024-07-20 19:06 UTC, Garima-149 commented
@4darsh-Dev I marked them already. 
Can I ask what levels you have assigned to issues I raised? Since, I made a single pr for all 5 issues.

2024-07-21 04:27 UTC, 4darsh-Dev commented
there was only single pr for all issues so , I gave max level3 
only points are counted from PRs labels, i thnk.

2024-07-21 05:28 UTC, Garima-149 commented
@4darsh-Dev okay I didn't know it before, otherwise I would have made multiple ones.

2024-07-21 10:38 UTC, 4darsh-Dev commented
not possible @Garima-149  now, 
it will look spammy, I have told you multiple times to not make single PR already, 
Will take care for the next times.

2024-08-12 08:42 UTC, 4darsh-Dev commented
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials